### ISSUE TITLE
Searching for a single quote gets escaped  

### ISSUE THREAD

**Issue by adardesign** [ajgon/alfred2-html-entity-lookup#1]
I am searching for a single quote `'` gets escaped of the entity search

![entity](https://cloud.githubusercontent.com/assets/23543/7359717/b997b8ae-ed0f-11e4-8a74-ab2156254ac6.png)

![singlequote](https://cloud.githubusercontent.com/assets/23543/7359696/8769b0f8-ed0f-11e4-98bf-02904e01ea54.png)

**Comment by Chrisedmo** [comment]
I was just about to comment the same thing! 

How can this be fixed?

**Comment by ajgon** [comment]
Hey,

I assume you meant `el` directive instead of `entity` since the latter is used only to resolve entity names (i.e. `entity quot`), so it won't work for a single quote anyway. However, the issue was also present in `el` and was fixed. 

Nice catch, thank you!

**Comment by adardesign** [comment]
Great, Thanks!
